# Generated by Django 5.1.5 on 2025-10-27 06:15

import django.core.validators
import django.db.models.deletion
import users.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='Nueva categoría', max_length=64)),
            ],
            options={
                'db_table': 'categoria',
                'db_table_comment': 'Categorías de productos',
            },
        ),
        migrations.CreateModel(
            name='OptionGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=40)),
            ],
            options={
                'db_table': 'grupo_opciones',
                'db_table_comment': 'Opciones que pueden modificar el precio de un servicio',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('nombre', models.CharField(max_length=128)),
                ('apellidos', models.CharField(max_length=128)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Negocio',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(default='Nuevo negocio', max_length=128)),
                ('descripcion', models.CharField(default='Descripción del negocio.', max_length=128)),
                ('direccion', models.CharField(default='Direccion', max_length=128)),
                ('telefono', models.CharField(blank=True, max_length=10)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('banner_img', models.ImageField(blank=True, default=None, null=True, upload_to=users.models.banner_img_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp'])])),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='negocios', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'negocio',
                'db_table_comment': 'Instancia del negocio autenticados',
            },
        ),
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=40)),
                ('precio', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opciones', to='users.optiongroup')),
            ],
            options={
                'db_table': 'opcion',
                'db_table_comment': 'Opciones que pueden modificar el precio de un servicio',
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='Nuevo producto', max_length=64)),
                ('descripcion', models.CharField(default='Agrega la descripción aquí...', max_length=128)),
                ('precio', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('visible', models.BooleanField(default=True)),
                ('imagen', models.ImageField(blank=True, default=None, null=True, upload_to=users.models.producto_img_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp'])])),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productos', to='users.categoria')),
                ('negocio', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='productos', to='users.negocio')),
            ],
            options={
                'db_table': 'producto',
                'db_table_comment': 'Productos del negocio',
            },
        ),
        migrations.AddField(
            model_name='optiongroup',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grupos', to='users.producto'),
        ),
        migrations.CreateModel(
            name='ProductoWrapper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anotacion', models.CharField(blank=True, default='', max_length=255)),
                ('opciones', models.ManyToManyField(to='users.option')),
                ('producto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.producto')),
            ],
            options={
                'db_table': 'producto_wrapper',
                'db_table_comment': 'Encapsulación para saber qué productos (y opciones) eligió una orden',
            },
        ),
        migrations.CreateModel(
            name='Orden',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveSmallIntegerField(default=0)),
                ('nombre_cliente', models.CharField(default='Sin nombre', max_length=128)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('negocio', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='ordenes', to='users.negocio')),
                ('productos', models.ManyToManyField(to='users.productowrapper')),
            ],
            options={
                'db_table': 'orden',
                'db_table_comment': 'Órdenes realizadas',
            },
        ),
    ]
