# Generated by Django 5.1.5 on 2025-10-24 05:42

import django.core.validators
import django.db.models.deletion
import users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='Nueva categoría', max_length=64)),
            ],
            options={
                'db_table': 'categoria',
                'db_table_comment': 'Categorías de productos',
            },
        ),
        migrations.CreateModel(
            name='OptionGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=40)),
            ],
            options={
                'db_table': 'grupo_opciones',
                'db_table_comment': 'Opciones que pueden modificar el precio de un servicio',
            },
        ),
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=40)),
                ('precio', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opciones', to='users.optiongroup')),
            ],
            options={
                'db_table': 'opcion',
                'db_table_comment': 'Opciones que pueden modificar el precio de un servicio',
            },
        ),
        migrations.CreateModel(
            name='OptionWrapper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grupo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.optiongroup')),
                ('opcion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.option')),
            ],
            options={
                'db_table': 'option_wrapper',
                'db_table_comment': 'Encapsulación para saber qué productos (y opciones) eligió una orden',
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='Nuevo producto', max_length=64)),
                ('descripcion', models.CharField(default='Agrega la descripción aquí...', max_length=128)),
                ('precio', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('imagen', models.ImageField(blank=True, default=None, null=True, upload_to=users.models.servicio_image_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp'])])),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productos', to='users.categoria')),
            ],
            options={
                'db_table': 'producto',
                'db_table_comment': 'Productos del negocio',
            },
        ),
        migrations.AddField(
            model_name='optiongroup',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grupos', to='users.producto'),
        ),
        migrations.CreateModel(
            name='ProductoWrapper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opciones', models.ManyToManyField(to='users.option')),
                ('producto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.producto')),
            ],
            options={
                'db_table': 'producto_wrapper',
                'db_table_comment': 'Encapsulación para saber qué productos (y opciones) eligió una orden',
            },
        ),
        migrations.CreateModel(
            name='Orden',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveSmallIntegerField(default=0)),
                ('nombre_cliente', models.CharField(default='Sin nombre', max_length=128)),
                ('fecha', models.DateTimeField(auto_now=True)),
                ('productos', models.ManyToManyField(to='users.productowrapper')),
            ],
            options={
                'db_table': 'orden',
                'db_table_comment': 'Órdenes realizadas',
            },
        ),
    ]
