# Generated by Django 5.2.7 on 2025-10-24 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_delete_optionwrapper'),
    ]

    operations = [
        migrations.AddField(
            model_name='productowrapper',
            name='anotacion',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
