# Generated by Django 5.1.5 on 2025-11-07 20:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_productowrapper_cantidad'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orden',
            old_name='productos',
            new_name='pedidos',
        ),
    ]
