# Generated by Django 5.2.7 on 2025-11-11 04:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_usuario_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='uuid',
            new_name='id',
        ),
    ]
