# Generated by Django 5.2.7 on 2025-11-11 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_rename_uuid_usuario_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='orden',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
    ]
