# Generated by Django 5.2.7 on 2025-11-11 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_orden_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='orden',
            name='estado',
            field=models.IntegerField(choices=[(0, 'Recibida'), (1, 'En proceso'), (2, 'Lista'), (3, 'Entregada'), (4, 'Cancelada')], default=0),
        ),
    ]
