# Generated by Django 5.1.5 on 2025-11-11 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_orden_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orden',
            name='estado',
            field=models.IntegerField(choices=[(0, 'En proceso'), (1, 'En proceso'), (2, 'Lista'), (3, 'Entregada'), (4, 'Cancelada')], default=0),
        ),
    ]
