# Generated by Django 5.2.7 on 2025-11-20 21:00

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_orden_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='negocio',
            field=models.ForeignKey(default=uuid.UUID('3c02f6c8-b916-424e-9bd0-0cb1334b3de2'), on_delete=django.db.models.deletion.CASCADE, related_name='categorias', to='users.negocio'),
        ),
        migrations.AlterField(
            model_name='option',
            name='descripcion',
            field=models.CharField(max_length=40, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(40)]),
        ),
        migrations.AlterField(
            model_name='optiongroup',
            name='descripcion',
            field=models.CharField(max_length=40, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(40)]),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
    ]
