# Generated by Django 5.2.7 on 2025-11-20 22:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_categoria_negocio_alter_option_descripcion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='negocio',
            name='slug',
            field=models.SlugField(blank=True, default='the-coffee-centro-mid', unique=True),
        ),
        migrations.AlterField(
            model_name='categoria',
            name='negocio',
            field=models.ForeignKey(default='3c02f6c8b916424e9bd00cb1334b3de2', on_delete=django.db.models.deletion.CASCADE, related_name='categorias', to='users.negocio'),
        ),
    ]
