# Generated by Django 5.2.7 on 2025-11-20 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_negocio_slug_alter_categoria_negocio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='negocio',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
