# Generated by Django 5.2.7 on 2025-11-20 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_alter_negocio_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='negocio',
            name='slug',
            field=models.SlugField(blank=True, default='the-coffee-centro-mid', unique=True),
        ),
    ]
