# Generated by Django 5.2.7 on 2025-12-03 16:39

import django.core.validators
import users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_alter_negocio_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='producto',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='categoria',
            name='nombre',
            field=models.CharField(default='Nueva categoría', max_length=48),
        ),
        migrations.AlterField(
            model_name='negocio',
            name='banner_img',
            field=models.ImageField(blank=True, default=None, null=True, storage=users.models.NegocioImgStorage, upload_to=users.models.banner_img_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp'])]),
        ),
        migrations.AlterField(
            model_name='negocio',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='imagen',
            field=models.ImageField(blank=True, default=None, null=True, storage=users.models.ProductoImgStorage, upload_to=users.models.producto_img_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp'])]),
        ),
    ]
