# Generated by Django 5.2.7 on 2025-12-03 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_producto_deleted_producto_deleted_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='categoria',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
