name: Try Deploy on Push 

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.12]

    steps:
      - name: SSH Deploy
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            cd ~/github
            git pull origin main
            cd backend
            source venv/bin/activate
            pip install -r requirements.txt
            python3 manage.py makemigrations
            python3 manage.py migrate
            systemctl restart gunicorn

            cd ..
            cd frontend
            pnpm install
            pnpm run build
            

            
            
